
# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        threads:
          max: 1000
          min-spare: 30
    port: 8088
    servlet:
      context-path: /api
spring:
    application:
      name: apitest
    mvc:
      static-path-pattern: /static/**
    profiles:
        active: db
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
    activiti:
#      database-schema-update: drop-create
#      database-schema-update: false
      database-schema-update: true
#      database-schema-update: create-drop
      check-process-definitions: false
#      historyLevel: none
#      historyLevel: activity
#       默认
      historyLevel: audit
#      historyLevel: full
      db-history-used: true
mybatis:
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
